def generate_key(num1: int, num2: int, num3: int) -> int:
    """
    You are given three positive integers num1, num2, and num3.

    The key of num1, num2, and num3 is defined as a four-digit number such that:
        Initially, if any number has less than four digits, it is padded with leading zeros.
        The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith
        digits of num1, num2, and num3.

    Return the key of the three numbers without leading zeros (if any).
    """

    nums_list = [str(i).zfill(4) for i in (num1, num2, num3)]
    gen_key = [0] * 4
    for i in range(4):
        digits = []
        for num in nums_list:
            digits.append(num[i])
        gen_key[i] = min(digits)
    return int("".join(gen_key))

print(generate_key(1, 10, 1000))
print(generate_key(987, 879, 798))